version: "3.9"

services:
  container:
    image: ghcr.io/biu7/taoli-tools-container-rdp:latest
    container_name: taoli-tools-container
    restart: always
    security_opt:
      - seccomp:./chromium.json
    volumes:
      - data:/home/taoli/data
      - tailscale:/var/lib/tailscale

volumes:
  data:
  tailscale:
