[Globals]
ini_version=1
fork=true
; Tailscale userspace networking forwards incoming TCP to loopback.
port=tcp://127.0.0.1:3389
runtime_user=xrdp
runtime_group=xrdp
tcp_nodelay=true
tcp_keepalive=true
security_layer=tls
certificate=/var/lib/xrdp/tls/cert.pem
key_file=/var/lib/xrdp/tls/key.pem
ssl_protocols=TLSv1.2, TLSv1.3
autorun=Xorg
allow_channels=true
allow_multimon=true
bitmap_cache=true
bitmap_compression=true
bulk_compression=true
max_bpp=32
new_cursors=true
use_fastpath=both

[Logging]
LogFile=/var/log/xrdp.log
LogLevel=INFO
EnableSyslog=false
EnableConsole=true
ConsoleLevel=INFO

[Channels]
rdpdr=true
rdpsnd=true
drdynvc=true
cliprdr=true
rail=true
xrdpvr=true

[Xorg]
name=Xorg
lib=libxup.so
username=ask
password=ask
port=-1
code=20
h264_frame_interval=16
rfx_frame_interval=32
normal_frame_interval=40
